name: cafeapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^1.3.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  fluttertoast: ^8.2.8
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.4
  pdf: ^3.11.1
  share_plus: ^10.0.2
  permission_handler: ^11.3.1
  esc_pos_printer_plus: ^0.1.1       # ✅ updated fork (image ^4 support)
  esc_pos_utils_plus: ^2.0.0         # ✅ updated fork (image ^4 support)
  image: ^4.2.0                      # ✅ latest compatible
  network_info_plus: ^5.0.3
  flutter_pdfview: ^1.3.2
  flutter_launcher_icons: ^0.13.1    # ✅ supports image ^4
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.0  # Add this for desktop support
  connectivity_plus: ^6.0.3
  path: ^1.9.0
  crypto: ^3.0.3
  cross_file: ^0.3.4+1
  flutter_dotenv: ^5.2.1

  # Desktop-specific
  window_manager: ^0.4.2
  file_picker: ^8.1.3
  desktop_drop: ^0.4.4
  printing: ^5.14.0
  flutter_styled_toast: ^2.2.1
  url_launcher: ^6.2.2



  # Google Sign-In
  googleapis: ^14.0.0
  google_sign_in: ^6.2.1

  # Firebase dependencies
  firebase_core: ^3.4.1
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_database: ^11.0.0
  http_parser: ^4.1.2
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  msix: ^3.16.6

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - .env

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open-sans.regular.ttf
        - asset: assets/fonts/open-sans.bold.ttf
          weight: 700

    - family: Amiri
      fonts:
        - asset: assets/fonts/amiri-regular.ttf
        - asset: assets/fonts/amiri-bold.ttf
          weight: 700

    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo-regular.ttf
        - asset: assets/fonts/cairo-bold.ttf
          weight: 700

    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/noto-sans-arabic.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# Add this MSIX configuration to your pubspec.yaml

msix_config:
  display_name: SIMS CAFE
  publisher_display_name: SIMS AI
  identity_name: com.sims.cafeapp
  msix_version: 1.0.0.0
  logo_path: assets/icon/icon.png  # Your app icon
  capabilities: internetClient
  
  # Optional: Add these for a professional look
  publisher: CN=SIMS
  start_menu_icon_path: assets/icon/icon.png
  tile_icon_path: assets/icon/icon.png
  
  # Optional: Specify icon sizes (Windows will auto-generate if not provided)
  icons_background_color: transparent