// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for Fuchsia.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmpMjCIqh4RVXmY19JRwZhK0S2NxpsaBk',
    appId: '1:964942933502:android:37f129dfabff854f9a64af',
    messagingSenderId: '964942933502',
    projectId: 'simscafe-c743e',
    storageBucket: 'simscafe-c743e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4b7wl4E-33NWBVVyKoMnYzK-mkt9IOWQ',
    appId: '1:964942933502:ios:b193122bc9c865e99a64af',
    messagingSenderId: '964942933502',
    projectId: 'simscafe-c743e',
    storageBucket: 'simscafe-c743e.firebasestorage.app',
    iosBundleId: 'com.example.cafeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4b7wl4E-33NWBVVyKoMnYzK-mkt9IOWQ',
    appId: '1:964942933502:ios:b193122bc9c865e99a64af',
    messagingSenderId: '964942933502',
    projectId: 'simscafe-c743e',
    storageBucket: 'simscafe-c743e.firebasestorage.app',
    iosBundleId: 'com.example.cafeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1ggenNDwBP6NZ3_pYH3htNCHBTS395O0',
    appId: '1:964942933502:web:03a2ad4b1092905c9a64af',
    messagingSenderId: '964942933502',
    projectId: 'simscafe-c743e',
    authDomain: 'simscafe-c743e.firebaseapp.com',
    storageBucket: 'simscafe-c743e.firebasestorage.app',
    measurementId: 'G-S6XPMZ1M3E',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyB1ggenNDwBP6NZ3_pYH3htNCHBTS39500',
    appId: '1:964942933502:web:0526735d40a11f4d9a64af',
    messagingSenderId: '964942933502',
    projectId: 'simscafe-c743e',
    storageBucket: 'simscafe-c743e.firebasestorage.app',
    authDomain: 'simscafe-c743e.firebaseapp.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ggenNDwBP6NZ3_pYH3htNCHBTS395O0',
    appId: '1:964942933502:web:0526735d40a11f4d9a64af',
    messagingSenderId: '964942933502',
    projectId: 'simscafe-c743e',
    authDomain: 'simscafe-c743e.firebaseapp.com',
    storageBucket: 'simscafe-c743e.firebasestorage.app',
    measurementId: 'G-S90YMKNLFF',
  );

}