// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not supported');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for Fuchsia.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmpMjCIqh4RVXmY19JRwZhK0S2NxpsaBk',
    appId: '1:964942933502:android:37f129dfabff854f9a64af',
    messagingSenderId: '964942933502',
    projectId: 'simscafe-c743e',
    storageBucket: 'simscafe-c743e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmpMjCIqh4RVXmY19JRwZhK0S2NxpsaBk',
    appId: '1:964942933502:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '964942933502',
    projectId: 'simscafe-c743e',
    storageBucket: 'simscafe-c743e.firebasestorage.app',
    iosBundleId: 'com.example.cafeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmpMjCIqh4RVXmY19JRwZhK0S2NxpsaBk',
    appId: '1:964942933502:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '964942933502',
    projectId: 'simscafe-c743e',
    storageBucket: 'simscafe-c743e.firebasestorage.app',
    iosBundleId: 'com.example.cafeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmpMjCIqh4RVXmY19JRwZhK0S2NxpsaBk',
    appId: '1:964942933502:android:37f129dfabff854f9a64af', // Use Android app ID for desktop
    messagingSenderId: '964942933502',
    projectId: 'simscafe-c743e',
    storageBucket: 'simscafe-c743e.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDmpMjCIqh4RVXmY19JRwZhK0S2NxpsaBk',
    appId: '1:964942933502:android:37f129dfabff854f9a64af', // Use Android app ID for desktop
    messagingSenderId: '964942933502',
    projectId: 'simscafe-c743e',
    storageBucket: 'simscafe-c743e.firebasestorage.app',
  );
}